name: Ejecutar InstaWebhooks Personal
on:
  schedule:
    - cron: '0 * * * *' # Se corre cada hora automáticamente
  workflow_dispatch:      # Esto te da el botón para probarlo YA

jobs:
  run-insta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalación
        run: pip install .
      - name: Ejecutar Bot
        run: instawebhooks --username "${{ secrets.IG_USER }}" --webhook "${{ secrets.DISCORD_URL }}"
