name: Ejecutar InstaWebhooks Personal
on:
  schedule:
    - cron: '0 * * * *' # Corre cada hora
  workflow_dispatch:      # Botón para correrlo a mano

jobs:
  run-insta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalación del Bot
        run: pip install .

      - name: Ejecutar Bot
        run: |
          instawebhooks "colombiateinspira" "${{ secrets.DISCORD_URL }}" -p 3
          instawebhooks "foto_sintesiss_" "${{ secrets.DISCORD_URL }}" -p 3
          instawebhooks "nevadodelruiz.co" "${{ secrets.DISCORD_URL }}" -p 3
          instawebhooks "parquelosnevados" "${{ secrets.DISCORD_URL }}" -p 3
          instawebhooks "santy_phai" "${{ secrets.DISCORD_URL }}" -p 3
          instawebhooks "its.magico" "${{ secrets.DISCORD_URL }}" -p 3
